on: [push]

jobs:
  sarif:
    runs-on: ubuntu-latest
    name: sarif multitool
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          arguments: 'help'
          
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"